#!/bin/bash

# Duplicate output to a log file
exec &> >(tee /tmp/flatpak-build-fw-$(date +"%F-%H%M%S").log)

set -xueo pipefail

# Delete the build dirs from last time. But then --keep-build-dirs, not --delete-build-dirs so that the build dirs from this time are left in place for optional inspection.
rm -rf .flatpak-builder/build 
flatpak-builder --user --repo=local-repo --keep-build-dirs --force-clean build-dir org.sil.FieldWorks.yml "$@"
flatpak --user remote-add --no-gpg-verify --if-not-exists local-repo ./local-repo
flatpak --user install --or-update --noninteractive local-repo org.sil.FieldWorks org.sil.FieldWorks.Debug