#!/bin/bash

# Duplicate output to a log file for easier inspection
exec &> >(tee /tmp/flatpak-build-$(date +"%F-%H%M%S").log)

set -xueo pipefail

PRODUCT="org.sil.WeSay"

XDG_CACHE_HOME="${XDG_CACHE_HOME-${HOME}/.cache}"
DEV_REPO_PATH="${XDG_CACHE_HOME}/dev-flatpak-repo"

# Delete the build dirs from last time. But then --keep-build-dirs, not --delete-build-dirs so that the build dirs from this time are left in place for optional inspection.
rm -rf .flatpak-builder/build
flatpak-builder --user --repo="${DEV_REPO_PATH}" --keep-build-dirs --no-shallow-clone --force-clean build-dir ${PRODUCT}.yml "$@"
flatpak --user remote-add --no-gpg-verify --if-not-exists local-dev-repo "${DEV_REPO_PATH}"
flatpak remove --assumeyes ${PRODUCT} ${PRODUCT}.Debug ${PRODUCT}.Locale || echo "flatpak was not already installed."
flatpak --user install --or-update --noninteractive local-dev-repo ${PRODUCT} ${PRODUCT}.Debug
