#!/bin/bash

set -x
set -ueo pipefail

# Share path to projects dir in dev repo in case projects dir is set to that location on dev machine.
DEV_PROJECTS_PATH="${HOME}"/fwrepo/fw/DistFiles/Projects

flatpak run -vv --devel --env=FW_DEBUG=true --filesystem="${DEV_PROJECTS_PATH}" "$@" org.sil.FieldWorks
